services:
  platform:
    build:
      context: ./platform
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - platform_data:/app/data
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://platform:3000
    depends_on:
      - platform
    restart: unless-stopped

volumes:
  platform_data: